export type LocalTask = { id: string; title: string; priority?: string; completed?: boolean };
export type SearchHistoryEntry = { id: string; origin: string; destination: string; date: string };
export type SavedAddress = { id: string; label: string; address: string };
export type ChatMessage = { role: string; content: string };
export type ChatSession = { id: string; title?: string; messages?: ChatMessage[] };
export const idbListLocalTasks = async (): Promise<LocalTask[]> => [];
export const idbListSearches = async (): Promise<Array<{ origin: string; destination: string; date: string }>> => [];
export const idbDeleteSearch = async (_id: string): Promise<void> => {};
export const idbListAddresses = async (): Promise<SavedAddress[]> => [];
export const idbAddAddress = async (_value: unknown): Promise<void> => {};
export const idbUpdateAddress = async (_id: string, _value: unknown): Promise<void> => {};
export const idbDeleteAddress = async (_id: string): Promise<void> => {};
export const idbReadRoutes = async (): Promise<unknown[]> => [];
export const idbReadSearchMeta = async (): Promise<unknown> => null;
export const idbWriteSearchMeta = async (_value: unknown): Promise<void> => {};
export const idbGetUserPrefs = async (): Promise<Record<string, any>> => ({});
export const idbSetUserPrefs = async (_prefs: unknown): Promise<void> => {};
export const idbListNotifications = async (): Promise<unknown[]> => [];
export const idbDismissNotification = async (_id: string): Promise<void> => {};
export const idbGetUserPrefsForNotifications = async (): Promise<Record<string, unknown>> => ({});
export const idbGetAllTaskSchedules = async (): Promise<unknown[]> => [];
export const idbGetTaskSchedule = async (_id: string): Promise<unknown> => null;
export const idbDeleteTaskSchedule = async (_id: string): Promise<void> => {};
export const idbGetPersistedActiveTask = async (): Promise<unknown> => null;
export const idbSetPersistedActiveTask = async (_value: unknown): Promise<void> => {};
export const idbClearPersistedActiveTask = async (): Promise<void> => {};
export const idbAddLocalTask = async (_value: unknown): Promise<void> => {};
export const idbUpdateLocalTask = async (_id: string, _value: unknown): Promise<void> => {};
export const idbSaveTaskElapsed = async (_id: string, _value: unknown): Promise<void> => {};
export const idbAddNotification = async (_value: unknown): Promise<void> => {};
export const idbSetTaskSchedule = async (_id: string, _value: unknown): Promise<void> => {};
export const idbListChatSessions = async (): Promise<ChatSession[]> => [];
export const idbReadChatSession = async (_id: string): Promise<ChatSession | null> => null;
export const idbWriteChatSession = async (_value: unknown): Promise<void> => {};
export const idbWriteChatMessage = async (_id: string, _value: unknown): Promise<void> => {};
export const idbDeleteChatSession = async (_id: string): Promise<void> => {};
